# Copyright (c) 2024 Hannes Mann, Alexander Wigren
# See LICENSE for details

# This is a list of native system apps for iOS, collected from the following sources:
# - https://support.apple.com/guide/deployment/bundle-ids-for-native-iphone-and-ipad-apps-depece748c41/web
# Native system apps are excluded for analysis
ios_system_apps = {
	"com.apple.appstore",
	"com.apple.barcodescanner",
	"com.apple.bridge",
	"com.apple.calculator",
	"com.apple.camera",
	"com.apple.clips",
	"com.apple.compass",
	"com.apple.documentsapp",
	"com.apple.facetime",
	"com.apple.findmy",
	"com.apple.fitness",
	"com.apple.freeform",
	"com.apple.health",
	"com.apple.home",
	"com.apple.ibooks",
	"com.apple.iclouddriveapp",
	"com.apple.imovie",
	"com.apple.journal",
	"com.apple.keynote",
	"com.apple.magnifier",
	"com.apple.maps",
	"com.apple.measure",
	"com.apple.mobileaddressbook",
	"com.apple.mobilecal",
	"com.apple.mobilegarageband",
	"com.apple.mobilemail",
	"com.apple.mobilenotes",
	"com.apple.mobilephone",
	"com.apple.mobilesafari",
	"com.apple.mobileslideshow",
	"com.apple.mobilesms",
	"com.apple.mobilestore",
	"com.apple.mobiletimer",
	"com.apple.music",
	"com.apple.news",
	"com.apple.numbers",
	"com.apple.pages",
	"com.apple.passbook",
	"com.apple.photo-booth",
	"com.apple.playgrounds",
	"com.apple.podcasts",
	"com.apple.preferences",
	"com.apple.reminders",
	"com.apple.shortcuts",
	"com.apple.stocks",
	"com.apple.store.jolly",
	"com.apple.tips",
	"com.apple.translate",
	"com.apple.tv",
	"com.apple.voicememos",
	"com.apple.weather"
}
