# This is the config file for the data collection and risk assessment server
# API keys are defined in secrets.toml

[server]
host = "localhost"
port = 8000

debug = false
log_requests = true
backend = "waitress"

# https://docs.sqlalchemy.org/en/20/core/engines.html#database-urls
database_url = "sqlite:///repository/development.db"

[logging]
level = "warning"
# If set to a non-empty string, write log to a file
# Example: "debug_{time:YYYY-MM-DD_HH:mm}.log"
file = ""

[importers]
# Configures if importers should be automatically added at startup
# This does not prevent users from adding importers manually (CSV upload, etc.)
autorun = true
# Configures the periodic timer for app info scanning
timer = 15

[analysis]
# Configures if app analyzers should be automatically added at startup
autorun = true
# Determines how the risk score is calculated for an application with multiple analyzers
risk_score_method_app = "max"
# Determines how the risk score is calculated for a device with multiple applications
risk_score_method_device = "max"
# Determines how the risk score is calculated for an entire organization
risk_score_method_organization = "avg"
# Configures the periodic timer for app analysis
# TODO: Add an option to run analysis only when an app has been updated from MDM
timer = 15

[analysis.gpt]
# Select the model that should be used for privacy policy analysis
# Recommended: gpt-4 or gpt-3.5-turbo
model = "gpt-4"

[analysis.permissions]
# Google maintains a list of 40 permissions marked as dangerous at https://developer.android.com/reference/android/Manifest.permission
# You can customize the permissions that are considered during analysis here
dangerous_permissions = [
	"android.permission.ACCEPT_HANDOVER",
	"android.permission.ACCESS_BACKGROUND_LOCATION",
	"android.permission.ACCESS_COARSE_LOCATION",
	"android.permission.ACCESS_FINE_LOCATION",
	"android.permission.ACCESS_MEDIA_LOCATION",
	"android.permission.ACTIVITY_RECOGNITION",
	"android.permission.ANSWER_PHONE_CALLS",
	"android.permission.BLUETOOTH_ADVERTISE",
	"android.permission.BLUETOOTH_CONNECT",
	"android.permission.BLUETOOTH_SCAN",
	"android.permission.BODY_SENSORS",
	"android.permission.BODY_SENSORS_BACKGROUND",
	"android.permission.CALL_PHONE",
	"android.permission.CAMERA",
	"android.permission.GET_ACCOUNTS",
	"android.permission.NEARBY_WIFI_DEVICES",
	"android.permission.POST_NOTIFICATIONS",
	"android.permission.PROCESS_OUTGOING_CALLS",
	"android.permission.READ_CALENDAR",
	"android.permission.READ_CALL_LOG",
	"android.permission.READ_CONTACTS",
	"android.permission.READ_EXTERNAL_STORAGE",
	"android.permission.READ_MEDIA_AUDIO",
	"android.permission.READ_MEDIA_IMAGES",
	"android.permission.READ_MEDIA_VIDEO",
	"android.permission.READ_MEDIA_VISUAL_USER_SELECTED",
	"android.permission.READ_PHONE_NUMBERS",
	"android.permission.READ_PHONE_STATE",
	"android.permission.READ_SMS",
	"android.permission.RECEIVE_MMS",
	"android.permission.RECEIVE_WAP_PUSH",
	"android.permission.RECORD_AUDIO",
	"android.permission.SEND_SMS",
	"android.permission.USE_SIP",
	"android.permission.UWB_RANGING",
	"android.permission.WRITE_CALENDAR",
	"android.permission.WRITE_CALL_LOG",
	"android.permission.WRITE_CONTACTS",
	"android.permission.WRITE_EXTERNAL_STORAGE",
	"com.android.voicemail.permission.ADD_VOICEMAIL"
]

[analysis.system_apps]
# This is a list of system apps for Android, collected from the following sources:
# - https://support.google.com/a/answer/7292363?hl=en
# - Google Pixel 2 XL after factory reset
#
# Since there are many different manufacturers of Android phones,
# it's not possible to cover all combinations so this is a "best effort" list
#
# System apps are excluded from analysis
android = [
	"android",
	"android.auto_generated_rro_vendor__",
	"com.android.backupconfirm",
	"com.android.bips",
	"com.android.bluetooth",
	"com.android.bluetoothmidiservice",
	"com.android.bookmarkprovider",
	"com.android.calllogbackup",
	"com.android.captiveportallogin.overlay",
	"com.android.carrierdefaultapp",
	"com.android.cellbroadcastreceiver",
	"com.android.certinstaller",
	"com.android.companiondevicemanager",
	"com.android.connectivity.metrics",
	"com.android.contacts",
	"com.android.cts.ctsshim",
	"com.android.cts.priv.ctsshim",
	"com.android.dreams.basic",
	"com.android.dynsystem",
	"com.android.egg",
	"com.android.emergency",
	"com.android.externalstorage",
	"com.android.facelock",
	"com.android.hotwordenrollment.okgoogle",
	"com.android.hotwordenrollment.xgoogle",
	"com.android.htmlviewer",
	"com.android.inputdevices",
	"com.android.internal.display.cutout.emulation.hole",
	"com.android.internal.display.cutout.emulation.waterfall",
	"com.android.keychain",
	"com.android.keyguard",
	"com.android.launcher",
	"com.android.localtransport",
	"com.android.location.fused",
	"com.android.managedprovisioning",
	"com.android.mms.service",
	"com.android.mtp",
	"com.android.musicfx",
	"com.android.nfc",
	"com.android.omadm.service",
	"com.android.ons",
	"com.android.pacprocessor",
	"com.android.phone",
	"com.android.printspooler",
	"com.android.providers.blockednumber",
	"com.android.providers.calendar",
	"com.android.providers.contacts",
	"com.android.providers.downloads.ui",
	"com.android.providers.downloads",
	"com.android.providers.media",
	"com.android.providers.partnerbookmarks",
	"com.android.providers.settings",
	"com.android.providers.telephony",
	"com.android.providers.userdictionary",
	"com.android.proxyhandler",
	"com.android.sdm.plugins.connmo",
	"com.android.sdm.plugins.dcmo",
	"com.android.sdm.plugins.diagmon",
	"com.android.sdm.plugins.sprintdm",
	"com.android.se",
	"com.android.server.telecom",
	"com.android.service.ims.presence",
	"com.android.service.ims",
	"com.android.settings",
	"com.android.sharedstoragebackup",
	"com.android.shell",
	"com.android.simappdialog",
	"com.android.soundpicker",
	"com.android.statementservice",
	"com.android.systemui.plugin.globalactions.wallet",
	"com.android.systemui",
	"com.android.traceur",
	"com.android.vending",
	"com.android.vpndialogs",
	"com.google.android.accessibility.soundamplifier",
	"com.google.android.captiveportallogin",
	"com.google.android.carrier",
	"com.google.android.carriersetup",
	"com.google.android.cellbroadcastservice",
	"com.google.android.configupdater",
	"com.google.android.contacts",
	"com.google.android.deskclock",
	"com.google.android.dialer",
	"com.google.android.documentsui",
	"com.google.android.euicc",
	"com.google.android.ext.services",
	"com.google.android.ext.shared",
	"com.google.android.feedback",
	"com.google.android.gms.location.history",
	"com.google.android.gms",
	"com.google.android.googlecamera",
	"com.google.android.googlequicksearchbox",
	"com.google.android.gsf.login",
	"com.google.android.gsf",
	"com.google.android.hardwareinfo",
	"com.google.android.hiddenmenu",
	"com.google.android.hotspot2.osulogin",
	"com.google.android.ims",
	"com.google.android.inputmethod.japanese",
	"com.google.android.inputmethod.korean",
	"com.google.android.inputmethod.latin",
	"com.google.android.inputmethod.pinyin",
	"com.google.android.markup",
	"com.google.android.marvin.talkback",
	"com.google.android.modulemetadata",
	"com.google.android.networkstack.permissionconfig",
	"com.google.android.networkstack.tethering.overlay",
	"com.google.android.networkstack.tethering",
	"com.google.android.networkstack",
	"com.google.android.nfcprovision",
	"com.google.android.onetimeinitializer",
	"com.google.android.overlay.googleconfig",
	"com.google.android.overlay.googlewebview",
	"com.google.android.overlay.permissioncontroller",
	"com.google.android.packageinstaller",
	"com.google.android.partnersetup",
	"com.google.android.permissioncontroller",
	"com.google.android.printservice.recommendation",
	"com.google.android.providers.media.module",
	"com.google.android.settings.intelligence",
	"com.google.android.setupwizard",
	"com.google.android.soundpicker",
	"com.google.android.storagemanager",
	"com.google.android.syncadapters.contacts",
	"com.google.android.tag",
	"com.google.android.tetheringentitlement",
	"com.google.android.tts",
	"com.google.android.webview",
	"com.google.android.wfcactivation",
	"com.google.android.wifi.resources",
	"com.google.ar.core",
	"com.google.audio.hearing.visualization.accessibility.scribe",
	"com.google.intelligence.sense",
	"com.google.mainline.telemetry",
	"com.google.modemservice",
	"com.google.vr.apps.ornament",
	"com.google.vr.vrcore",
	"com.samsung.android.contacts",
	"com.samsung.android.phone"
]

# This is a list of system apps for iOS, collected from the following sources:
# - https://support.apple.com/guide/deployment/bundle-ids-for-native-iphone-and-ipad-apps-depece748c41/web
#
# System apps are excluded from analysis
ios = [
	"com.apple.appstore",
	"com.apple.barcodescanner",
	"com.apple.bridge",
	"com.apple.calculator",
	"com.apple.camera",
	"com.apple.clips",
	"com.apple.compass",
	"com.apple.documentsapp",
	"com.apple.facetime",
	"com.apple.findmy",
	"com.apple.fitness",
	"com.apple.freeform",
	"com.apple.health",
	"com.apple.home",
	"com.apple.ibooks",
	"com.apple.iclouddriveapp",
	"com.apple.imovie",
	"com.apple.journal",
	"com.apple.keynote",
	"com.apple.magnifier",
	"com.apple.maps",
	"com.apple.measure",
	"com.apple.mobileaddressbook",
	"com.apple.mobilecal",
	"com.apple.mobilegarageband",
	"com.apple.mobilemail",
	"com.apple.mobilenotes",
	"com.apple.mobilephone",
	"com.apple.mobilesafari",
	"com.apple.mobileslideshow",
	"com.apple.mobilesms",
	"com.apple.mobilestore",
	"com.apple.mobiletimer",
	"com.apple.music",
	"com.apple.news",
	"com.apple.numbers",
	"com.apple.pages",
	"com.apple.passbook",
	"com.apple.photo-booth",
	"com.apple.playgrounds",
	"com.apple.podcasts",
	"com.apple.preferences",
	"com.apple.reminders",
	"com.apple.shortcuts",
	"com.apple.stocks",
	"com.apple.store.jolly",
	"com.apple.tips",
	"com.apple.translate",
	"com.apple.tv",
	"com.apple.voicememos",
	"com.apple.weather"
]
