# This file contains your personal API keys
# It should NOT be commited to git

[api]
# API key for OpenAI GPT-3.5/GPT-4
openai = ""
# API key for Exodus Privacy
# https://github.com/Exodus-Privacy/exodus/blob/v1/doc/api.md
exodus = ""
