# This file contains your personal API keys
# It should NOT be commited to git

[api]
# API key for OpenAI GPT-3.5/GPT-4
openai = ""
# API key for Exodus Privacy
# https://github.com/Exodus-Privacy/exodus/blob/v1/doc/api.md
exodus = ""

# See docs/intune.md for more information on getting this section set up
[api.msgraph]
authority = "https://login.microsoftonline.com/tenant_id"
# Client ID for Microsoft Graph
client_id = ""
scope = ["https://graph.microsoft.com/.default"]
# Client secret for Microsoft Graph
secret = ""
endpoint = "https://graph.microsoft.com/v1.0/users"
